// <auto-generated />
namespace MyWeb.Migrations.SqlFunding
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPOId_Amortisasi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPOId_Amortisasi));
        
        string IMigrationMetadata.Id
        {
            get { return "201804230727067_AddPOId_Amortisasi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
