// <auto-generated />
namespace MyWeb.Migrations.SqlFunding
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrateBreakAmortisasi002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrateBreakAmortisasi002));
        
        string IMigrationMetadata.Id
        {
            get { return "201609090842492_migrateBreakAmortisasi002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
