// <auto-generated />
namespace MyWeb.Migrations.SqlFunding
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddKeterangan_detailbarang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddKeterangan_detailbarang));
        
        string IMigrationMetadata.Id
        {
            get { return "201803020724103_AddKeterangan_detailbarang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
