// <auto-generated />
namespace MyWeb.Migrations.SqlFunding
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TambahInsertTableUploadNasabah : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TambahInsertTableUploadNasabah));
        
        string IMigrationMetadata.Id
        {
            get { return "201811010332015_TambahInsertTableUploadNasabah"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
