// <auto-generated />
namespace MyWeb.Migrations.SqlFunding
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatejurnalpembayaran : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatejurnalpembayaran));
        
        string IMigrationMetadata.Id
        {
            get { return "201609020653458_updatejurnalpembayaran"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
