// <auto-generated />
namespace MyWeb.Migrations.SqlStatement
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TambahTableInsertLog1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TambahTableInsertLog1));
        
        string IMigrationMetadata.Id
        {
            get { return "201810120249219_TambahTableInsertLog1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
