// <auto-generated />
namespace MyWeb.Migrations.SqlStatement
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _Migrate_006 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Migrate_006));
        
        string IMigrationMetadata.Id
        {
            get { return "201808230728314__Migrate_006"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
